export const SET_USER_ROLE_REQUEST = "SET_USER_ROLE_REQUEST"
export const SET_USER_ROLE_SUCCESS = "SET_USER_ROLE_SUCCESS"
export const SET_USER_ROLE_FAILED = "SET_USER_ROLE_FAILED"

export const GET_JOB_POST_REQUEST = "GET_JOB_POST_REQUEST";
export const GET_JOB_POST_SUCCESS = "GET_JOB_POST_SUCCESS";
export const GET_JOB_POST_FAILED = "GET_JOB_POST_FAILED";
export const SET_CURRENT_EMPLOYEE = "SET_CURRENT_EMPLOYEE";
export const RECALL_API = "RECALL_API";

export const GET_TASK_REQUEST = "GET_TASK_REQUEST";
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS";
export const GET_TASK_FAILED = "GET_TASK_FAILED";

export const GET_JOB_TITLE_REQUEST = "GET_JOB_TITLE_REQUEST";
export const GET_JOB_TITLE_SUCCESS = "GET_JOB_TITLE_SUCCESS";
export const GET_JOB_TITLE_FAILED = "GET_JOB_TITLE_FAILED";

export const GET_CANDIDATE_REQUEST = "GET_CANDIDATE_REQUEST";
export const GET_CANDIDATE_SUCCESS = "GET_CANDIDATE_SUCCESS";
export const GET_CANDIDATE_FAILED = "GET_CANDIDATE_FAILED";

export const GET_COMPANY_REQUEST = "GET_COMPANY_REQUEST";
export const GET_COMPANY_SUCCESS = "GET_COMPANY_SUCCESS";
export const GET_COMPANY_FAILED = "GET_COMPANY_FAILED";
