export const GET_JOB_POST_REQUEST = "GET_JOB_POST_REQUEST";
export const GET_JOB_POST_SUCCESS = "GET_JOB_POST_SUCCESS";
export const GET_JOB_POST_FAILED = "GET_JOB_POST_REQUEST";
export const SET_CURRENT_EMPLOYEE = "SET_CURRENT_EMPLOYEE";