export const GET_JOB_POST_REQUEST = "GET_JOB_POST_REQUEST";
export const GET_JOB_POST_SUCCESS = "GET_JOB_POST_SUCCESS";
export const GET_JOB_POST_FAILED = "GET_JOB_POST_FAILED";
export const SET_CURRENT_EMPLOYEE = "SET_CURRENT_EMPLOYEE";
export const RECALL_API = "RECALL_API";
export const GET_TASK_REQUEST = "GET_TASK_REQUEST";
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS";
export const GET_TASK_FAILED = "GET_TASK_FAILED";
